### ISSUE TITLE
Installation fails due to conflicting pyyaml version

### ISSUE THREAD

**Issue by NeolithEra** [garyd203/ssmash#39]
Hi, users are unable to run **_ssmash_** due to dependency conflict with _**pyyaml**_ package. As shown in the following full dependency graph of **_ssmash_**, **_ssmash_** requires _**pyyaml >=5.1,<6**_，while **_flying-circus_** requires **_<5.2.0,>=5.1.1_**.

According to pip’s _“first found wins”_ installation strategy, _**pyyaml 5.2**_ is the actually installed version. However, _**pyyaml 5.2**_ does not satisfy **_PyYAML<5.2.0,>=5.1.1_**.

### Dependency tree-----------
```
ssmash - 2.0.1
| +- click(install version:7.0 version range:>=7.0,<8)
| +- flying-circus(install version:0.7.2 version range:>=0.7,<0.8)
| | +- attrs(install version:19.3.0 version range:>=18.2.0)
| | +- inflection(install version:0.3.1 version range:<0.4,>=0.3.1)
| | +- pyyaml(install version:3.13 version range:<5.2.0,>=5.1.1)
| +- inflection(install version:0.3.1 version range:==0.3.1)
| +- pyyaml(install version:5.2 version range:>=5.1,<6)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix your direct dependency to be **_pyyaml <5.2.0_**. I have checked this revision will not affect your downstream projects now.
2.	Remove your direct dependency **_pyyaml_**, and use **_pyyaml_** transitively introduced by **_flying-circus_**.

3.	Ask your upstream project **flying-circus** to loose the version range of **_pyyaml_**.

@garyd203 Which solution do you prefer, 1, 2 or 3?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by garyd203** [comment]
Hi @NeolithEra , thanks a lot for the detailed bug report. This issue hadn't affected me because I have been using `poetry` to install (which does resolve the `PyYAML` versions in a compatible way), rather than `pip`, so thanks for bringing it to my attention.

For a solution, it's not desirable to loosen the `PyYAML` version range for `flying-circus` (which is somewhat coupled to the internals of `PyYAML`), unfortunately.

The best approach seems to be if we restrict our version of `PyYAML` to something compatible (say, "PyYAML>=5.1,<5.2") - your option (1). Are you happy to put together a PR along those lines?

**Comment by garyd203** [comment]
I will pick this up

**Comment by garyd203** [comment]
Appears to be resolved now. Thanks @NeolithEra :)

```
$ docker run -it python:3.6 "bash"
root:/# pip install ssmash
/ ... /
Installing collected packages: click, inflection, PyYAML, attrs, flying-circus,
ssmash
Successfully installed PyYAML-5.1.2 attrs-18.2.0 click-7.0 flying-circus-0.7.2 i
nflection-0.3.1 ssmash-2.1.2

root:/# ssmash --help
Usage: ssmash [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...

  Convert a plain YAML file with application configuration into a
  CloudFormation template with SSM parameters.

Options:
  -i, --input, --input-file FILENAME
                                  Where to read the application configuration
                                  YAML file
  -o, --output, --output-file FILENAME
                                  Where to write the CloudFormation template
                                  file
  --description TEXT              The description for the CloudFormation
                                  stack.
  --help                          Show this message and exit.

Commands:
  invalidate-ecs     Invalidate the cache in an ECS Service that uses these...
  invalidate-lambda  Invalidate the cache in a Lambda Function that uses...
```
